version: '3'

services:
  finaxysapp:
    image: finaxysapp
    build:
      context: .\FinaxysApp
      dockerfile: Dockerfile
    depends_on: 
     - sqlserver

  finaxysdata:
    image: finaxysdata
    build:
      context: .\FinaxysData
      dockerfile: Dockerfile
    depends_on: 
     - sqlserver

  sqlserver:
    image: microsoft/mssql-server-windows-developer
    environment:
      - SA_PASSWORD="TEST@a14"
      - ACCEPT_EULA="Y"
    