version: '3'

services:
  finaxysapp:
    image : dtrfinaxys-cloud-expo.westeurope.cloudapp.azure.com/finaxys/app
    ports:
      - "52751"
    deploy:
      placement:
         constraints: [node.platform.OS == windows]

  finaxysdata:
    image : dtrfinaxys-cloud-expo.westeurope.cloudapp.azure.com/finaxys/data
    depends_on: 
     - dbserversql
    deploy:
      placement:
         constraints: [node.platform.OS == windows]

  dbserversql:
    image: microsoft/mssql-server-windows-express
    ports:
      - "1433:1433"
    environment:
      - sa_password=TEST@a14
      - ACCEPT_EULA=Y
    deploy:
      placement:
         constraints: [node.platform.OS == windows]
  finaxysclient:
    image : dtrfinaxys-cloud-expo.westeurope.cloudapp.azure.com/finaxys/angular
    ports:
      - 4200:4200
    deploy:
      placement:
         constraints: [node.platform.OS == linux]
    
